core/urls.py
from django.urls import path

from . import views


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('order-summary/', views.order_summary, name='order_summary'),
    path('add-to-cart/<slug:slug>',
         views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug:slug>',
         views.remove_from_cart, name='remove_from_cart'),
    path('remove-single-item-from-cart/<slug:slug>',
         views.remove_single_item_from_cart,
         name='remove_single_item_from_cart'),
    path('empty-cart/', views.empty_cart, name='empty_cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('addresses/', views.AddressListView.as_view(), name='address_list'),
    path('create-address/',
         views.AddressCreateView.as_view(), name='create_address'),
    path('update-address/<int:pk>/',
         views.AddressUpdateView.as_view(), name='update_address'),
    path('delete-address/<int:pk>/',
         views.AddressDeleteView.as_view(), name='delete_address'),
    path('set-selected-address/<int:address_id>/',
         views.set_selected_address, name='set_selected_address'),
    # Session based cart urls
    # path('cart/', views.view_cart, name='cart'),
    # path('add-to-cart-session/<slug:slug>',
    #     views.add_to_cart_session, name='add_to_cart_session'),
    # path('remove-from-cart-session/<slug:slug>',
    #     views.remove_from_cart_session, name='remove_from_cart_session'),
    # path('remove-single-item-from-cart-session/<slug:slug>',
    #     views.remove_single_item_from_cart_session,
    #     name='remove_single_item_from_cart_session'),
    # path('empty-cart-session/',
    #     views.empty_cart_session, name='empty_cart_session'),
]

siparisver/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
]

templates/addresses/address_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <div class="px-4 py-4 max-w-7xl mx-auto">
    <form class="px-4 py-6 bg-white rounded-lg border shadow-md" method="post">
      {% csrf_token %}
      <p class="text-xl"><span class="font-semibold">"{{ object }}"</span> adresini silmek istediğinizden emin misiniz?</p>
      <div class="text-right">
        <button class="mt-4 mr-4 px-4 py-2 bg-red-500 text-white font-semibold tex-sm rounded hover:bg-red-600 focus:outline-none focus:shadow-outline" type="submit">Adresi Sil <i class="fas fa-trash"></i></button>
        <a href="{% url 'core:address_list' %}" class="px-6 py-3 bg-gray-300 font-semibold rounded text-sm hover:bg-gray-400 focus:outline-none focus:shadow-outline">İptal</a>
      </div>
    </form>
  </div>
{% endblock content %}

templates/addresses/address_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="px-4 py-4 max-w-7xl mx-auto">
    <h2 class="py-10 uppercase text-center text-2xl leading-tight text-gray-600 font-semibold">ADRESLERİM</h2>

    
    
    
    <div class="border border-b-0 bg-white rounded-lg shadow-md">
      {% if addresses.count > 0 %}
        {% for address in addresses %}
          <div class="px-4 py-6 relative overflow-hidden border-b">
            <h2 class="text-xl font-semibold">{{ address.title }}</h2>      
            <p class="text-gray-600">{{ address.text }}</p>
            {% if address == user.selected_address %}
              <p class="absolute right-0 top-0 px-4 py-2 text-green-500">Seçili Adres <i class="far fa-check-circle"></i></p>
            {% else %}
              <div class="mt-4 text-right">
                <a href="{% url 'core:set_selected_address' address_id=address.pk %}" class="text-blue-500 hover:text-blue-600">Seçili adres olarak ayarla &#x279c;</a>
              </div>
            {% endif %}
            <div class="mt-4 flex items-center justify-between">
              <div>
                <a href="{% url 'core:update_address' pk=address.pk %}" class="px-4 py-2 bg-gray-300 rounded font-semibold text-sm hover:bg-gray-400 focus:outline-none focus:shadow-outline">Düzenle <i class="fas fa-edit"></i></a>
              </div>
              <div>
                <a href="{% url 'core:delete_address' pk=address.pk %}" class="px-4 py-2 text-lg text-red-500 hover:text-red-600"><i class="fas fa-trash"></i></a>
              </div>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <div class="px-4 py-6 sm:flex sm:items-center sm:justify-between">
          <div class="w-full sm:w-1/2 mr-4">
            <p class="text-gray-600">Henüz bir adres eklemediniz. Adres eklemek için tıklayın.</p>
          </div>
          <div class="w-full sm:w-1/2">
            <a href="{% url 'core:create_address' %}" class="mt-4 sm:mt-0 block px-4 py-2 bg-blue-500 text-xl font-semibold text-white rounded-full w-full text-center hover:bg-blue-600 shadow-md">Adres Ekle <span class="float-right">&#x279c;</span></a>
          </div>
        </div>
      {% endif %}
    </div>

    {% if addresses.count > 0 %}
      <div class="mt-4 text-right">
        <a href="{% url 'core:create_address' %}" class="px-10 py-2 block sm:inline bg-green-400 text-xl font-semibold text-white rounded-full w-full text-center hover:bg-green-500 shadow-md">Yeni Adres Ekle <span class="float-right sm:float-none">&#x279c;</span></a>
      </div>
    {% endif %}
  </div>
{% endblock content %}

templates/addresses/create_address.html
{% extends 'base.html' %}

{% block content %}
  <div class="px-4 py-4 max-w-7xl mx-auto">
    <h2 class="py-10 uppercase text-center text-2xl leading-tight text-gray-600 font-semibold">YENİ ADRES EKLE</h2>

     <form name="addressForm" method="post" class="w-full">
      {% csrf_token %}
      {% load form_utils %}
      {% for field in form %}
        <p id="{{ field.name }}">
          <h4 class="mb-2 text-xl font-semibold mt-4">{{ field.label_tag }}</h4>
          {{ field | placeholder:field.label | addclass:'px-2 py-1 bg-white border rounded w-full focus:outline-none focus:shadow-outline'}}
          {% for error in field.errors %}
            <p class="text-red-600 text-sm form-error">{{ error }}</p>
            <script type="text/javascript">
              document.addressForm.{{field.name}}.classList.remove('border')
              document.addressForm.{{field.name}}.classList.add('border-red-500', 'border-2');
            </script>
          {% endfor %}
          {% if field.help_text %}
            <small class="text-gray-600">{{ field.help_text }}</small>
          {% endif %}
        </p>
      {% endfor %}
      <button type="submit" class="float-right mt-4 px-4 w-full sm:w-auto py-2 bg-green-500 text-white font-bold text-center rounded-full focus:outline-none focus:shadow-outline hover:bg-green-600">Adresi Kaydet <span class="float-right sm:float-none">&#x279c;</span></button>
    </form>
  </div>
{% endblock content %}

templates/addresses/update_address.html
{% extends 'base.html' %}

{% block content %}
  <div class="px-4 py-4 max-w-7xl mx-auto">
    <h2 class="py-10 uppercase text-center text-2xl leading-tight text-gray-600 font-semibold">ADRES DÜZENLE</h2>

     <form name="addressForm" method="post" class="w-full">
      {% csrf_token %}
      {% load form_utils %}
      {% for field in form %}
        <p id="{{ field.name }}">
          <h4 class="mb-2 text-xl font-semibold mt-4">{{ field.label_tag }}</h4>
          {{ field | placeholder:field.label | addclass:'px-2 py-1 bg-white border rounded w-full focus:outline-none focus:shadow-outline'}}
          {% for error in field.errors %}
            <p class="text-red-600 text-sm form-error">{{ error }}</p>
            <script type="text/javascript">
              document.addressForm.{{field.name}}.classList.remove('border')
              document.addressForm.{{field.name}}.classList.add('border-red-500', 'border-2');
            </script>
          {% endfor %}
          {% if field.help_text %}
            <small class="text-gray-600">{{ field.help_text }}</small>
          {% endif %}
        </p>
      {% endfor %}
      <button type="submit" class="float-right mt-4 px-4 w-full sm:w-auto py-2 bg-green-500 text-white font-bold text-center rounded-full focus:outline-none focus:shadow-outline hover:bg-green-600">Adresi Kaydet <span class="float-right sm:float-none">&#x279c;</span></button>
    </form>
  </div>
{% endblock content %}