core/urls.py
from django.urls import path

from . import views


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('order-summary/', views.order_summary, name='order_summary'),
    path('add-to-cart/<slug:slug>',
         views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug:slug>',
         views.remove_from_cart, name='remove_from_cart'),
    path('remove-single-item-from-cart/<slug:slug>',
         views.remove_single_item_from_cart,
         name='remove_single_item_from_cart'),
    path('empty-cart/', views.empty_cart, name='empty_cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('addresses/', views.AddressListView.as_view(), name='address_list'),
    path('create-address/',
         views.AddressCreateView.as_view(), name='create_address'),
    path('update-address/<int:pk>/',
         views.AddressUpdateView.as_view(), name='update_address'),
    path('delete-address/<int:pk>/',
         views.AddressDeleteView.as_view(), name='delete_address'),
    path('set-selected-address/<int:address_id>/',
         views.set_selected_address, name='set_selected_address'),
    # Session based cart urls
    # path('cart/', views.view_cart, name='cart'),
    # path('add-to-cart-session/<slug:slug>',
    #     views.add_to_cart_session, name='add_to_cart_session'),
    # path('remove-from-cart-session/<slug:slug>',
    #     views.remove_from_cart_session, name='remove_from_cart_session'),
    # path('remove-single-item-from-cart-session/<slug:slug>',
    #     views.remove_single_item_from_cart_session,
    #     name='remove_single_item_from_cart_session'),
    # path('empty-cart-session/',
    #     views.empty_cart_session, name='empty_cart_session'),
]

siparisver/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
]

templates/partials/navbar/_account_dropdown.html
<div class="ml-3 relative">
  <div>
    <button class="account-dropdown-button flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-red-500 transition duration-150 ease-in-out">
      <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
    </button>
  </div>
  <div class="account-dropdown-list hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg">
    <div class="py-1 rounded-md bg-white shadow-xs">
      <a href="#" class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out">Your Profile</a>
      <a href="#" class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out">Settings</a>
      <a href="{% url 'account_logout' %}" class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out">Sign out</a>
    </div>
  </div>
</div>

templates/partials/navbar/_navbar_old.html
<header class="bg-white border-b shadow">
  <div class="container mx-auto px-2 sm:px-6 lg:px-8 py-2">
    <div class="flex items-center justify-between">
      <div class="flex items-center">
        <a href="{% url 'core:index' %}" class="mr-4">
          <i class="fas fa-utensils text-3xl align-middle text-red-500"></i>
          <span class="hidden sm:inline ml-1 text-xl font-extrabold align-middle">Sipariş Ver</span>
        </a>
        <a href="{% url 'core:product_list' %}" class="px-4 py-1 font-bold rounded hover:bg-gray-300 focus:outline-none">Menü</a>
      </div>
      
      <div class="flex items-center">
        {% if user.is_authenticated %}
          {% include 'partials/navbar/_account_dropdown.html' %}
        {% else %}
          <a href="{% url 'account_login' %}" class="px-2 py-1 bg-green-500 text-white font-bold rounded">
            <i class="fas fa-sign-in-alt"></i>
            <span class="ml-1 hidden sm:inline">Giriş Yap</span>
          </a>
        {% endif %}
      </div>
    </div>
  </div>
</header>

<script>
  $('.account-dropdown-button').click(function () {
    // $('.account-dropdown-list').toggleClass('hidden');
    $('.account-dropdown-list').fadeToggle();
  });
</script>